- name: variables declaration from files
  hosts: localhost
  vars_files:
  - vars.yml
    
  tasks:
  - name: variable override
    ansible.builtin.debug:
      msg: "learnig {{course}} from  {{trainer}}"