- name: Default values
  hosts: localhost
  
  vars: 
    greeting: "hello world"
    numbers: [1, 2, 3, 1, 4 ]
    my_dict:
     course: Ansible
     trainer: Arun

  tasks:
  - name: print default value
    ansible.builtin.debug:
     msg: "{{ course | default('Ansible')}}"

  - name: print in upper case
    ansible.builtin.debug:
     msg: "{{ greeting | upper}}"
  
  - name: remove duplicates
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"

  - name: dictonary to items
    ansible.builtin.debug:
     msg: "{{ my_dict | dict2items }}"